### ISSUE TITLE
More than 3 sip account

### ISSUE THREAD

**Issue by Bonbon604** [arnonym/ha-plugins#97]
Hi guyz,

Is it possible to use more than only the 3 existing account can be found in the configuration?
The idea is to use more caller ID so I know which automation triggers the call.

**Comment by Bonbon604** [comment]
I use one account for doorbell, the second one if my brother approaching and so on.
I'd like to use different caller ID's so I know which automation triggered my call.

**Comment by arnonym** [comment]
Are you using different `incoming_call_file`s on the same SIP account for that? Because you could do that with one SIP account and do something like this: https://github.com/arnonym/ha-plugins/issues/86#issuecomment-1898825610

So use a home assistant condition to serve different menus based on the number.
